### ISSUE TITLE
raise exception_class(message, screen, stacktrace)

### ISSUE THREAD

**Issue by ankursrivasa** [bewestphal/SeleniumAI#6]
Hi ,

Can you plz help me out how I can handle this exception?

**Comment by ankursrivasa** [comment]
done, took 21888.643 seconds
Cleaning up Selenium driver and docker container
Traceback (most recent call last):
  File "example/run_example.py", line 8, in <module>
    kickoff(configuration=configuration)
  File "/home/administrator/Downloads/Selenium-AI-master/package/kickoff.py", line 28, in kickoff
    run_in_train_mode(dqn, configuration)
  File "/home/administrator/Downloads/Selenium-AI-master/package/kickoff.py", line 48, in run_in_train_mode
    configuration.environment.selenium_docker_wrapper.clean()
  File "/home/administrator/Downloads/Selenium-AI-master/package/driver.py", line 70, in clean
    self.driver and self.driver.quit()
  File "/home/administrator/anaconda3/envs/webagent/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 698, in quit
    self.execute(Command.QUIT)
  File "/home/administrator/anaconda3/envs/webagent/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/administrator/anaconda3/envs/webagent/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: None

**Comment by Amith-K-A** [comment]
post complete stack trace.

**Comment by ankursrivasa** [comment]
Screenshot: available via screen
Stacktrace:
    at java.util.concurrent.FutureTask.get (FutureTask.java:205)
    at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout (SimpleTimeLimiter.java:128)
    at org.openqa.selenium.net.UrlChecker.waitUntilUnavailable (UrlChecker.java:120)
    at org.openqa.selenium.remote.service.DriverService.stop (DriverService.java:214)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute (DriverCommandExecutor.java:94)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:637)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:694)
    at org.openqa.selenium.remote.RemoteWebDriver.quit (RemoteWebDriver.java:533)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke (EventFiringWebDriver.java:104)
    at com.sun.proxy.$Proxy4.quit (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver.quit (EventFiringWebDriver.java:202)
    at org.openqa.selenium.remote.server.handler.DeleteSession.call (DeleteSession.java:50)
    at org.openqa.selenium.remote.server.handler.DeleteSession.call (DeleteSession.java:29)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)

**Comment by Amith-K-A** [comment]
still, it is not a complete stack trace.

**Comment by ankursrivasa** [comment]
This is the comlete error msg I am getting in my terminal:

done, took 21888.643 seconds
Cleaning up Selenium driver and docker container
Traceback (most recent call last):
  File "example/run_example.py", line 8, in <module>
    kickoff(configuration=configuration)
  File "/home/administrator/Downloads/Selenium-AI-master/package/kickoff.py", line 28, in kickoff
    run_in_train_mode(dqn, configuration)
  File "/home/administrator/Downloads/Selenium-AI-master/package/kickoff.py", line 48, in run_in_train_mode
    configuration.environment.selenium_docker_wrapper.clean()
  File "/home/administrator/Downloads/Selenium-AI-master/package/driver.py", line 70, in clean
    self.driver and self.driver.quit()
  File "/home/administrator/anaconda3/envs/webagent/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 698, in quit
    self.execute(Command.QUIT)
  File "/home/administrator/anaconda3/envs/webagent/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/administrator/anaconda3/envs/webagent/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: None
Screenshot: available via screen
Stacktrace:
    at java.util.concurrent.FutureTask.get (FutureTask.java:205)
    at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout (SimpleTimeLimiter.java:128)
    at org.openqa.selenium.net.UrlChecker.waitUntilUnavailable (UrlChecker.java:120)
    at org.openqa.selenium.remote.service.DriverService.stop (DriverService.java:214)
    at org.openqa.selenium.remote.service.DriverCommandExecutor.execute (DriverCommandExecutor.java:94)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:637)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:694)
    at org.openqa.selenium.remote.RemoteWebDriver.quit (RemoteWebDriver.java:533)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke (EventFiringWebDriver.java:104)
    at com.sun.proxy.$Proxy4.quit (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver.quit (EventFiringWebDriver.java:202)
    at org.openqa.selenium.remote.server.handler.DeleteSession.call (DeleteSession.java:50)
    at org.openqa.selenium.remote.server.handler.DeleteSession.call (DeleteSession.java:29)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:176)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    at java.lang.Thread.run (Thread.java:745)
(webagent) administrator@administrator-virtual-machine:~/Downloads/Selenium-AI-master$

**Comment by Amith-K-A** [comment]
it is due to your docker selenium setup, try restarting docker.

**Comment by ankursrivasa** [comment]
ok.. will try.. thanks

**Comment by ankursrivasa** [comment]
thnks Brian.. will try

**Comment by ankursrivasa** [comment]
I checked for lesser steps.

Training for 100 steps ...
2019/12/03 11:31:08 I1203 11:31:08.470691 26398 gymvnc.go:374] [0:127.0.0.1:32776] update queue max of 60 reached; pausing further updates
2019/12/03 11:31:08 I1203 11:31:08.649798 26398 gymvnc.go:278] [0:127.0.0.1:32776] resuming updates
Interval 1 (0 steps performed)
  100/10000 [..............................] - ETA: 3162s - reward: -0.0700done, took 33.938 seconds
Cleaning up Selenium driver and docker container
(webagent) administrator@administrator-virtual-machine:~/Downloads/Selenium-AI-master$ 


I guess it worked.
Thanks Brian

**Comment by ankursrivasa** [comment]
in the example u have used test.html file.

How can I give my web app as the input to the program?

and one more

I want to view what's happening in VNC viewer.. what should I do?

Please reply

**Comment by Amith-K-A** [comment]
@ankursrivasa I am not sure about how to use this, for VNC you need to install vnc and need to log in with credentials printed on your console.

**Comment by ankursrivasa** [comment]
ok.. thanks Brian for the input.

**Comment by Amith-K-A** [comment]
@ankursrivasa FYI my name is Amith
